### ISSUE TITLE
Loss of precision when converting measurements to SDS and back

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-server#95] opened 2020-10-30 16:47 UTC
Comparison of the three code bases (RCPCHGrowth, LMSGrowth and SITAR) reveals loss of precision in the process of generating SDS from measurements and back.

**Comment by statist7** [comment] 2020-11-02 15:17
I have checked LMSgrowth and my own R code to test the precision of converting to z-score and back again. R has median 16 digits of precision whereas LMSgrowth has 5.

We have already seen this with LMSgrowth, that using the same base z-score for the different measurements leads to z-scores varying in the the fifth place.

Doing the conversion from measurement to z-score and back to measurement gives the result explicitly - the results are rounded to 5 digits, with zeroes in the 6th and later places.

This makes me think we should not use LMSgrowth as the gold standard, and instead use my R code as a "silver" standard.

To this end I'm trying to make the flask client read my CSV file to make the comparison, but it is flaky. Should I use the REACT client instead, and if so, how?

**Comment by pacharanero** [comment] 2020-11-02 16:01
The React client can do spreadsheets in a similar way to the Flask one, at

https://growth.rcpch.ac.uk/spreadsheet

Let me know if you have any problems.

**Comment by statist7** [comment] 2020-11-02 18:30
Thanks @pacharanero.

I've tried this .csv file (zipped here) which I think is ok, as I've fixed the date format and removed the NAs. But it doesn't do anything with it. Am I missing something?

[RCPCH as posted edited.csv.zip](https://github.com/rcpch/digital-growth-charts-server/files/5477196/RCPCH.as.posted.edited.csv.zip)

**Comment by pacharanero** [comment] 2020-11-03 19:35
Hmmmm I've looked at the React client upload feature and it doesn't seem to be doing anything. There are no javascript errors in the console. We need to take a look at this @eatyourpeas at some point.

**Comment by eatyourpeas** [comment] 2020-11-03 22:00
this is my fault I am sorry. When I refactored out the measurement_type
class I did not do this for the spreadsheet endpoint. It is searching for a
measurement_type which does not exist and throws an error.
I will fix this.

**Comment by eatyourpeas** [comment] 2020-11-03 22:10
This should now be fixed in commit8b23c39
<https://github.com/rcpch/digital-growth-charts-server/commit/8b23c39b74b0a35d9287d87062a35a82362b4386>
to
unstable branch

**Comment by pacharanero** [comment] 2020-11-04 09:20
I've confirmed this is now fixed and working at 
https://rcpch-dgc-react-client-unstable.azurewebsites.net/

**Comment by pacharanero** [comment] 2020-11-04 09:25
I've pulled the changes into `alpha` which means they should be live and usable at https://growth.rcpch.ac.uk/ within about 8 minutes

**Comment by statist7** [comment] 2020-11-04 09:37
Thanks - this works. 

There's no download button, but I've copied and pasted the window, which seems to work.

Two comments: the dates are in mm/dd/yyyy format. 

And in row 256 (see attached file) the measurement date is missing. It may be because of the early gestation, 22+6.
[RCPCH as posted edited output.txt](https://github.com/rcpch/digital-growth-charts-server/files/5486876/RCPCH.as.posted.edited.output.txt)

**Comment by pacharanero** [comment] 2020-11-04 09:47
OK, have you enough you can work with for today? We will look at those issues

**Comment by statist7** [comment] 2020-11-04 10:02
Yes, no prob

--
Population Policy and Practice
UCL Great Ormond Street Institute of Child Health,
30 Guilford Street, London WC1N 1EH, UK

**Comment by statist7** [comment] 2020-11-04 10:34
Further observations on the output, just for info - no hurry.

I can't now get the upload to work, either with the react client or rcpch.

100 extraneous lines are added to the end of the output file, all consisting of bmi `17.77` at age `15.39767`, with SDS `-0.888265` or `-1.064261` depending on pre/term.

**Comment by eatyourpeas** [comment] 2020-11-10 20:25
This is being dealt with elsewhere so closing this.

**Comment by statist7** [comment] 2021-01-19 16:43
Sorry, I can't find the relevant issue for this.

I'm using the RCPCHgrowth googlesheet to test randomly generated data. I've generated a test file in R and copied and pasted it into the sheet, but it gives these errors. I'm sure the relevant columns are numbers not characters.

Is there a bug, or am I doing something wrong?

![RCPCHgrowth Screenshot 2021-01-19 at 16 24 39](https://user-images.githubusercontent.com/5055653/105064182-79236100-5a74-11eb-855a-84adaed0129f.png)

And here's the file itself. 

[csv test 1000 for RCPCH.txt](https://github.com/rcpch/digital-growth-charts-server/files/5837298/csv.test.1000.for.RCPCH.txt)

**Comment by eatyourpeas** [comment] 2021-01-19 19:53
No worries @statist7 - this was more of a side project and so there is nowhere really to post questions. This is as good a place as any.
I think you have included a new column A which has knocked all the parameters out. If you look at the attached image you select the cell at the end of the row and then enter the cells from b onwards in that order. I am sure there must be a way for google sheets to create a tooltip to remind you of the parameter order as you enter them but i have not found it yet. Also, make sure (as you have) that the dates are in the format YYYY-MM-DD otherwise it breaks. I will fix these issues in due course.

![image](https://user-images.githubusercontent.com/1058647/105085120-3ae76b00-5a8f-11eb-8dd1-d8c82715a422.png)

**Closed as completed** 2021-01-19 19:53 UTC
Labels: mvp

**Comment by statist7** [comment] 2021-01-20 12:34
Sorry, that was clottish of me.

However I'm still struggling. I have formatted the two date columns as ISO 8601 format, made sure the arguments all line up, and validated the two columns as dates, but it still says that they are not valid dates. 

??

**Comment by eatyourpeas** [comment] 2021-01-20 14:20
Not your fault at all
It definitely needs improiving
The dates have to be YYY-MM-DD ( I think I told you the wrong format) and they have to be a string (not a date)
This bit I will tidy up
I have done your ~4000 rows and looks fine
Let me know if you have any further problems

**Comment by statist7** [comment] 2021-01-20 14:44
Thanks @eatyourpeas - it's good to see it working.

**Comment by statist7** [comment] 2021-01-21 19:02
I've now been able to compare LMSgrowth with RCPCHgrowth and it throws up genuine errors! There are 16 entries where the sds discrepancy exceeds 0.005.

They are for four very preterm children aged >2 whose corrected ages are <2. So the preterm not the term reference should be used.

**Comment by eatyourpeas** [comment] 2021-01-21 19:51
Thanks @statist7 . This issue is closed and not really related so I will create a new issue. There must be an error as you say as to which reference is selected at 2y.
