### ISSUE TITLE
Instructions page won't load

### ISSUE THREAD

**Issue by andrewpalmeruk** [rcpch/digital-growth-charts-server#47] opened 2020-07-08 12:29 UTC
On our Windows builds, the Instructions page errors with:
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

the Traceback was:
127.0.0.1 - - [08/Jul/2020 12:01:44] "?[35m?[1mGET /instructions HTTP/1.1?[0m" 500 -
Traceback (most recent call last):
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
StopIteration: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\andrewp\Documents\GC\digital-growth-charts-flask-client\app.py", line 150, in instructions
    return render_template("instructions.html", fill=html.json())
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\andrewp\AppData\Local\Programs\Python\Python38-32\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by pacharanero** [comment] 2020-08-25 18:28
I've confirmed that this issue does still exist and affects the live Flask client

**Comment by pacharanero** [comment] 2020-09-09 11:47
This issue has been fixed - it was actually the client crashing because of some missing data in the server response.
As of today the live Flask client is working fine on the Instructions endpoint. Closing.

**Closed by pacharanero** 2020-09-09 11:47 UTC
