### ISSUE TITLE
Reverse look-up for z-scores

### ISSUE THREAD

**Issue by statist7** [rcpch/digital-growth-charts-server#23] opened 2020-06-08 10:41 UTC
The API is designed to accept dates and measurements and convert them to z-scores. This represents the typical clinical scenario, where a child has been measured and needs to be assessed.

However there is also a need to do the reverse conversion, from z-score to measurement. The most obvious example of this is to obtain the values need to draw the chart centiles, where each centile curve corresponds to a particular z-score. This might be viewed as more a research than a clinical requirement, and hence non-MVP, but I'm not so sure.

We have already discussed returning the measurements corresponding to specified centiles, to be used to draw the chart. I argue that we could generalise this by allowing the request to include a set of centiles (and corresponding set of ages) for which the corresponding measurements would be returned.

For the MVP the z-scores could default to the nine-centile format and the age range to the first year, but it would be worth keeping the spec general for non-MVP.

**Comment by eatyourpeas** [comment] 2020-11-22 11:46
this is actually a duplicate of #23. Closing here.

**Closed by eatyourpeas** 2020-11-22 11:46 UTC
Labels: duplicate
